name: Documentation request
description: Propose to add documentation or example.
labels: "documentation"
body:
  - type: textarea
    id: why
    attributes:
      label: Why do we need this documentation or example?
      description: Ideally, explain why a combination of existing docs or examples cannot be used instead.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Describe the proposal.
      description: Include a description of what should be documented or shown using a new example, including the feature subset that will be covered.
    validations:
      required: true
