name: Documentation request
description: Propose a new feature.
labels: "enhancement"
body:
  - type: textarea
    id: why
    attributes:
      label: Why do we need this feature?
      description: Ideally, explain why a combination of existing features cannot be used instead.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Describe the proposal.
      description: Include a detailed description of the feature, with usage examples.
    validations:
      required: true
  - type: textarea
    id: platform
    attributes:
      label: Is the feature specific to an operating system, compiler, or build system version?
      description: If it is, please specify which versions.
    validations:
      required: false
