name: Refactor request
description: Propose a new tidy, refactor or convention change.
labels: "refactor"
body:
  - type: textarea
    id: why
    attributes:
      label: What's wrong with the code as it stands?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Describe the proposal.
      description: Include a detailed description of the change, with an example.
    validations:
      required: true
