name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CC: clang
  CXX: clang++

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Tests
      run: bazel test --test_output=errors //...

    - name: AddressSanitizer
      run: bazel test -c dbg --config=asan --test_output=errors //...

    - name: UndefinedBehaviorSanitizer
      run: bazel test -c dbg --config=ubsan --test_output=errors //...

    - name: ThreadSanitizer
      run: bazel test -c dbg --config=tsan --test_output=errors //...

  MacOs:
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Tests
      run: bazel test --test_output=errors //...


  Windows:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Tests
      run: bazel test --test_output=errors //...
