name: ci

on:
  push:
  pull_request:

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Tests
      run: bazel test --test_output=errors //...

    - name: Tests with Address Sanitizer
      run: bazel test -c dbg --config=asan --test_output=errors //...

    - name: Tests with Undefined Behavior Sanitizer
      run: bazel test -c dbg --config=ubsan --test_output=errors //...

    - name: Tests with Thread Sanitizer
      run: bazel test -c dbg --config=tsan --test_output=errors //...

  MacOs:
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Tests
      run: bazel test --test_output=errors //...

    - name: Tests with Address Sanitizer
      run: bazel test -c dbg --config=asan --test_output=errors //...

    - name: Tests with Undefined Behavior Sanitizer
      run: bazel test -c dbg --config=ubsan --test_output=errors //...

    - name: Tests with Thread Sanitizer
      run: bazel test -c dbg --config=tsan --test_output=errors //...

  Windows:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Tests
      run: bazel test --test_output=errors //...

    - name: Tests with Address Sanitizer
      run: bazel test -c dbg --config=asan --test_output=errors //...

    - name: Tests with Undefined Behavior Sanitizer
      run: bazel test -c dbg --config=ubsan --test_output=errors //...

    - name: Tests with Thread Sanitizer
      run: bazel test -c dbg --config=tsan --test_output=errors //...
